import type { Metadata } from 'next'
import { ActiveToc } from '@/components/active-toc'
import { Callout, PageHeader, Section } from '@/components/page'

export const metadata:Metadata={title:'Design alignment'}
const toc=[['Readiness','readiness'],['Shared contract','contract'],['Complex products','scale'],['Operating model','operating-model'],['Rollout','rollout'],['Sources','sources']] as const
const checks=[
  ['Instance, not imitation','The visual unit is an instance from the published library—not a detached copy, local duplicate, or look-alike frame.','Design'],
  ['A real component boundary','Repeated UI has a Figma component and a production component. Pages and one-off layout frames stay unconnected.','Design + code'],
  ['Props express intent','Variants, booleans, text, and instance swaps describe the public choices; layer names and deep overrides do not carry the contract.','Design'],
  ['Tokens carry decisions','Color, spacing, type, radius, and elevation use governed variables/styles with intentional modes and code-token aliases.','System'],
  ['Composition is predictable','Named slots expose direct, approved child instances. Deep accidental nesting is not treated as an API.','Design + code'],
  ['Parity is explicit','Every supported Figma option maps to code, or is marked design-only/code-only with an owner and resolution.','Team'],
]
const rollout=[
  ['Inventory','Use library analytics, repository usage, and designer interviews to find the 10–20 components that are stable and used most.'],
  ['Reconcile','Pair one designer and one engineer. Agree names, options, defaults, slots, tokens, and unsupported states in a contract table.'],
  ['Pilot','Connect one simple, one variant-heavy, and one composed component. Test in real handoffs across at least two products.'],
  ['Gate','Parse mappings in CI; review Figma library changes and code API changes together; publish from an owned release path.'],
  ['Expand','Add components only after the pilot’s defects have owners. Track coverage by actual instances—not raw component count.'],
]

export default function Alignment(){return <div className="container docs-layout"><article><PageHeader eyebrow="Design operations · before mapping" title="Code Connect starts with a shared component contract." description="The mapping can translate two healthy systems. It cannot turn detached artwork, ambiguous component properties, token drift, and mismatched APIs into one system. Align the design library, code library, and team workflow first."/>
<div className="alignment-thesis" aria-label="The Code Connect readiness equation"><div><span>Figma</span><strong>Reusable instance</strong><small>intent + properties + tokens</small></div><b>↔</b><div><span>Shared contract</span><strong>Parity decisions</strong><small>names + defaults + composition</small></div><b>↔</b><div><span>Code</span><strong>Public component API</strong><small>imports + props + children</small></div></div>
<Section id="readiness" eyebrow="01 · Readiness" title="Six conditions make a component connectable"><p className="body-copy">Treat these as a per-component checklist, not a demand to clean the entire organization first. A mapping is ready when the team can answer each row without inspecting hidden layers or relying on tribal knowledge.</p><div className="readiness-list">{checks.map(([title,description,owner],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{description}</p></div><small>{owner}</small></article>)}</div><Callout tone="red" title="Do not connect visual coincidence">If three products have similar cards with different behavior, do not force one universal component. Connect their stable leaves first, document the divergence, and converge the parent only when product and engineering owners agree.</Callout></Section>
<Section id="contract" eyebrow="02 · Shared contract" title="Make the conversation concrete"><p className="body-copy">For each candidate, review one small contract table in the same session. The artifact matters more than matching terminology: it exposes gaps before somebody writes a brittle mapping.</p><div className="contract-visual"><div className="contract-head"><strong>Button</strong><span>Reviewed · Design + Web + iOS</span></div>{[['Intent','Figma property','Code API','Decision'],['Emphasis','Hierarchy: Primary','variant="primary"','Translate'],['Size','Size: Medium','size="md"','Translate'],['Busy','—','loading','Code-only'],['Icon','Leading: instance swap','icon={<… />}','Approved slot'],['Surface','color/action/primary','var(--action-primary)','Token alias']].map((row,i)=><div className={i===0?'contract-row labels':'contract-row'} key={row[0]}>{row.map(cell=><span key={cell}>{cell}</span>)}</div>)}</div><div className="alignment-rules">{[['Prefer semantic names','Use “Emphasis” or “Tone,” not “Blue” or “Style 2.” Map names when Figma and code vocabulary reasonably differ.'],['Keep defaults aligned','The omitted/default value should render the same thing in design and code. Otherwise snippets look right only by accident.'],['Expose supported choice','Use component properties for decisions consumers may make. Do not expose every internal layer as a prop.'],['Record asymmetry','Design-only explorations and code-only behavioral props are valid. Mark them explicitly instead of inventing a false mapping.']].map(([h,p])=><article key={h}><h3>{h}</h3><p>{p}</p></article>)}</div></Section>
<Section id="scale" eyebrow="03 · Many products, deep trees" title="Federate the edges; standardize the contract"><div className="scale-diagram"><div className="scale-core"><span>Core library</span><strong>Button · Icon · Text · Field</strong><small>strict contract + shared tokens</small></div><div className="scale-lines"><i/><i/><i/></div><div className="scale-products">{[['Product A','Core + approved theme'],['Product B','Core + local composites'],['Legacy C','Adapter + migration queue']].map(([a,b])=><div key={a}><strong>{a}</strong><small>{b}</small></div>)}</div></div><ul className="principle-list"><li><strong>Connect leaves before containers.</strong> Stable buttons, icons, badges, and fields survive more product variation than large screens or deeply nested cards.</li><li><strong>Use explicit slots.</strong> Keep connected children direct and ordered; wrappers used only for layout should not become an invisible contract.</li><li><strong>Allow qualified mappings.</strong> One Figma component may need platform/package-specific mappings; one visually similar family may need separate product components.</li><li><strong>Create an exception lane.</strong> Label local experiments and legacy components, provide a supported replacement, and set a review date—do not silently detach.</li></ul></Section>
<Section id="operating-model" eyebrow="04 · Communication" title="Replace convention reminders with a small operating system"><div className="operating-grid">{[['At design time','Library component picker first; detach only with a documented reason. Provide starter kits and office hours for teams under delivery pressure.'],['At library review','Designer and engineer review the contract table, token use, nesting, defaults, accessibility states, and migration impact.'],['At code review','Component API changes require a mapping impact check. Mapping changes require parse/preview evidence and a design reviewer.'],['At handoff','Developer checks the selected instance is connected and the generated snippet is plausible; reports drift through one intake path.'],['Every month','Triage broken mappings, detached-instance hotspots, unmapped popular components, and exceptions approaching their review date.'],['Ownership','Name a design-system DRI and an engineering DRI, plus product-library stewards. Publish response times and escalation paths.']].map(([h,p])=><article key={h}><span>{h}</span><p>{p}</p></article>)}</div><Callout title="A practical policy for non-compliance">Do not block all design work. Use three states: <strong>ready</strong> (connected and supported), <strong>candidate</strong> (may be used; needs reconciliation), and <strong>exception</strong> (local or legacy, with owner and expiry). Make the compliant path faster with searchable assets, examples, and pairing—not policing alone.</Callout></Section>
<Section id="rollout" eyebrow="05 · Adoption plan" title="Start narrow and measure behavior"><div className="rollout-timeline">{rollout.map(([h,p],i)=><article key={h}><span>{i+1}</span><div><h3>{h}</h3><p>{p}</p></div></article>)}</div><div className="measure-grid">{[['Adoption','% of inspected UI instances from an approved library'],['Coverage','% of high-use component instances with reviewed mappings'],['Fidelity','handoffs where snippet uses the intended package/API'],['Health','broken or stale mappings; median time to repair'],['Drift','detaches, local duplicates, and unresolved parity decisions']].map(([h,p])=><div key={h}><strong>{h}</strong><span>{p}</span></div>)}</div><p className="body-copy small">Avoid “number of mappings” as the primary KPI. It rewards connecting low-value components and says nothing about whether designers use them or developers trust the output.</p></Section>
<Section id="sources" eyebrow="Research notes" title="Sources and field signals"><p className="body-copy">The recommendations above combine official product guidance with recurring implementation questions from practitioners. GitHub issues are useful field signals, not a statistically representative survey.</p><div className="source-list"><a href="https://developers.figma.com/docs/code-connect/" target="_blank" rel="noreferrer"><strong>Figma · Code Connect documentation</strong><span>Product model, supported workflow, Dev Mode output, and setup guidance. ↗</span></a><a href="https://help.figma.com/hc/en-us/articles/360056440594-Create-and-use-component-properties" target="_blank" rel="noreferrer"><strong>Figma · Component properties</strong><span>Variant, boolean, text, and instance-swap properties used to expose component decisions. ↗</span></a><a href="https://help.figma.com/hc/en-us/articles/15343816063383-Modes-for-variables" target="_blank" rel="noreferrer"><strong>Figma · Variable modes</strong><span>How one variable collection represents contexts such as themes and breakpoints. ↗</span></a><a href="https://github.com/figma/code-connect/issues/11" target="_blank" rel="noreferrer"><strong>Community signal · nested properties</strong><span>A long-running request illustrates why hidden nested decisions complicate clean mappings. ↗</span></a><a href="https://github.com/figma/code-connect/issues/291" target="_blank" rel="noreferrer"><strong>Community signal · monitoring drift</strong><span>A practitioner request for alerts when Figma props change or mappings fail. ↗</span></a><a href="https://github.com/figma/code-connect/issues/365" target="_blank" rel="noreferrer"><strong>Community signal · nested instances</strong><span>A concrete tension between reusable nesting and exposing every child as a component property. ↗</span></a></div></Section>
</article><ActiveToc items={toc}/></div>}
